
spring.application.name=employee_management
spring.datasource.url=jdbc:postgresql://localhost:5432/admin
spring.datasource.username=postgres
spring.datasource.password=iniyan1842006
spring.jpa.hibernate.ddl-auto=update